org.gradle.jvmargs=-Xmx1536m
org.gradle.java.home=/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home
android.useAndroidX=true
android.enableJetifier=true
kapt.jvmargs=--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac=ALL-UNNAMED
kapt.use.worker.api=false
